/**
 * CelesTrak SATCAT `OWNER` code -> readable country / operator name.
 *
 * The GP element sets the plugin fetches carry no ownership; SATCAT does, keyed
 * by the same NORAD id. OWNER is a country of registry for state actors and an
 * operator/consortium for commercial fleets (Intelsat, SES, ...), which is the
 * honest attribution for those objects. Codes follow CelesTrak's published
 * source list (celestrak.org/satcat/sources.php); unmapped codes fall through
 * to the raw code rather than being dropped.
 */

const OWNERS: Record<string, string> = {
  AB: 'Abu Dhabi',
  ALG: 'Algeria',
  ANG: 'Angola',
  ARGN: 'Argentina',
  ASRA: 'Austria',
  AUS: 'Australia',
  AZER: 'Azerbaijan',
  BEL: 'Belgium',
  BELA: 'Belarus',
  BERM: 'Bermuda',
  BGD: 'Bangladesh',
  BHUT: 'Bhutan',
  BOL: 'Bolivia',
  BRAZ: 'Brazil',
  BUL: 'Bulgaria',
  CA: 'Canada',
  CHBZ: 'China/Brazil',
  CHLE: 'Chile',
  CIS: 'Russia (CIS)',
  COL: 'Colombia',
  CRI: 'Costa Rica',
  CZCH: 'Czechia',
  DEN: 'Denmark',
  ECU: 'Ecuador',
  EGYP: 'Egypt',
  ESA: 'European Space Agency',
  ESRO: 'European Space Research Organisation',
  EST: 'Estonia',
  ETH: 'Ethiopia',
  EUME: 'EUMETSAT',
  EUTE: 'Eutelsat',
  FGER: 'France/Germany',
  FIN: 'Finland',
  FR: 'France',
  FRIT: 'France/Italy',
  GER: 'Germany',
  GHA: 'Ghana',
  GLOB: 'Globalstar',
  GREC: 'Greece',
  GUAT: 'Guatemala',
  HUN: 'Hungary',
  IM: 'Inmarsat',
  IND: 'India',
  INDO: 'Indonesia',
  IRAN: 'Iran',
  IRAQ: 'Iraq',
  IRID: 'Iridium',
  IRL: 'Ireland',
  ISRA: 'Israel',
  ISS: 'International Space Station',
  IT: 'Italy',
  ITSO: 'Intelsat',
  JPN: 'Japan',
  KAZ: 'Kazakhstan',
  KEN: 'Kenya',
  LAOS: 'Laos',
  LKA: 'Sri Lanka',
  LTU: 'Lithuania',
  LUXE: 'Luxembourg',
  MA: 'Morocco',
  MALA: 'Malaysia',
  MCO: 'Monaco',
  MDA: 'Moldova',
  MEX: 'Mexico',
  MMR: 'Myanmar',
  MNG: 'Mongolia',
  NATO: 'NATO',
  NETH: 'Netherlands',
  NICO: 'New ICO',
  NIG: 'Nigeria',
  NKOR: 'North Korea',
  NOR: 'Norway',
  NPL: 'Nepal',
  NZ: 'New Zealand',
  O3B: 'O3b Networks',
  ORB: 'ORBCOMM',
  PAKI: 'Pakistan',
  PERU: 'Peru',
  POL: 'Poland',
  POR: 'Portugal',
  PRC: 'China',
  QAT: 'Qatar',
  ROC: 'Taiwan',
  ROM: 'Romania',
  RP: 'Philippines',
  RWA: 'Rwanda',
  SAFR: 'South Africa',
  SAUD: 'Saudi Arabia',
  SDN: 'Sudan',
  SEAL: 'Sea Launch',
  SES: 'SES',
  SING: 'Singapore',
  SKOR: 'South Korea',
  SPN: 'Spain',
  STCT: 'Singapore/Taiwan',
  SWED: 'Sweden',
  SWTZ: 'Switzerland',
  THAI: 'Thailand',
  TMMC: 'Turkmenistan/Monaco',
  TUN: 'Tunisia',
  TURK: 'Turkey',
  UAE: 'United Arab Emirates',
  UK: 'United Kingdom',
  UKR: 'Ukraine',
  UNK: 'Unknown',
  URY: 'Uruguay',
  US: 'United States',
  USBZ: 'US/Brazil',
  VENZ: 'Venezuela',
  VTNM: 'Viet Nam',
  ZWE: 'Zimbabwe',
  // Codes confirmed present in the live SATCAT catalog beyond the core list.
  TBD: 'Unassigned',
  ABS: 'ABS',
  BHR: 'Bahrain',
  BWA: 'Botswana',
  DJI: 'Djibouti',
  GRSA: 'Greece/Saudi Arabia',
  HRV: 'Croatia',
  JOR: 'Jordan',
  KWT: 'Kuwait',
  MNE: 'Montenegro',
  RASC: 'RascomStar',
  SLB: 'Solomon Islands',
  SVK: 'Slovakia',
  SVN: 'Slovenia',
};

/** Readable owner/country for a SATCAT OWNER code; '' when absent. */
export function ownerToCountry(code: string | undefined | null): string {
  if (!code) return '';
  const key = code.trim().toUpperCase();
  if (!key) return '';
  return OWNERS[key] ?? key;
}
